"""Generate markdown triage reports from diagnosis results."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from ..models import DiagnosisReport, Classification, Confidence


_ICON = {
    Classification.PRODUCT_BUG: "🐛",
    Classification.INFRA_ISSUE: "🔧",
    Classification.TEST_ISSUE: "🧪",
    Classification.UNKNOWN: "❓",
}

_CONF_ICON = {
    Confidence.HIGH: "🟢",
    Confidence.MEDIUM: "🟡",
    Confidence.LOW: "🔴",
}


def generate_markdown_report(report: DiagnosisReport, feature: str = "") -> str:
    """Generate a markdown triage report.

    Args:
        report: The diagnosis report to render.
        feature: Optional feature name for the header.

    Returns:
        Formatted markdown string.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Agentic QA Triage Report",
        f"**Feature**: {feature}" if feature else "",
        f"**Generated**: {now}",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Count |",
        f"|--------|-------|",
        f"| Total Tests | {report.total_tests} |",
        f"| Passed | {report.passed} |",
        f"| Failed | {report.failed} |",
        f"| Skipped | {report.skipped} |",
        "",
        f"> {report.summary}",
        "",
    ]

    if not report.failures:
        lines.append("**No failures to diagnose.** All tests passed.")
        return "\n".join(lines)

    # Classification breakdown
    counts: dict[Classification, int] = {}
    for d in report.failures:
        counts[d.classification] = counts.get(d.classification, 0) + 1

    lines.append("## Classification Breakdown")
    lines.append("")
    for cls, count in sorted(counts.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"- {_ICON.get(cls, '')} **{cls.value}**: {count}")
    lines.append("")

    # Individual diagnoses sorted by severity
    severity_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    sorted_failures = sorted(
        report.failures,
        key=lambda d: severity_order.get(d.severity.value, 99),
    )

    lines.append("## Failure Details")
    lines.append("")

    for i, diag in enumerate(sorted_failures, 1):
        icon = _ICON.get(diag.classification, "")
        conf_icon = _CONF_ICON.get(diag.confidence, "")

        lines.append(f"### {i}. {diag.test_name}")
        lines.append("")
        lines.append(
            f"| Classification | Confidence | Severity |"
        )
        lines.append(f"|----------------|------------|----------|")
        lines.append(
            f"| {icon} {diag.classification.value} | "
            f"{conf_icon} {diag.confidence.value} | "
            f"**{diag.severity.value}** |"
        )
        lines.append("")
        lines.append(f"**Probable Cause**: {diag.probable_cause}")
        lines.append("")
        lines.append(f"**Evidence**: {diag.evidence_summary}")
        lines.append("")
        lines.append(f"**Recommended Action**: {diag.recommended_action}")
        lines.append("")

        # Differential diagnosis table
        lines.append("<details>")
        lines.append("<summary>Differential Diagnosis</summary>")
        lines.append("")
        for h in diag.hypotheses:
            lines.append(f"**{h.classification.value}**")
            if h.evidence_for:
                lines.append("- Evidence FOR: " + "; ".join(h.evidence_for))
            if h.evidence_against:
                lines.append("- Evidence AGAINST: " + "; ".join(h.evidence_against))
            lines.append("")
        lines.append("</details>")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("")
    lines.append(
        "*This report was generated by [AI Test Generator]"
        "(https://github.com/vazidmansuri005/ai-test-generator). "
        "Classifications are AI-assessed — always verify before taking action.*"
    )

    return "\n".join(lines)


def save_report(report: DiagnosisReport, output_path: str | Path, feature: str = "") -> Path:
    """Generate and save a markdown report to a file."""
    md = generate_markdown_report(report, feature)
    path = Path(output_path)
    path.write_text(md)
    return path
